### ISSUE TITLE
Improve Header by removing sudden changes

### ISSUE THREAD

**Issue by meinhoonharsh** [gdscrgpv/gdscrgpv#1]
#### Description
Whenever we scroll from the top of the website, the navbar suddenly changes to the blue background. It must be done with something smooth effect that can be anything like a fade, slide or appearing like a wave, etc.

#### Screenshots
![gdscheader](https://user-images.githubusercontent.com/64343449/136683401-6d077e59-bb81-4801-bc3a-3bf6399966e9.gif)

#### Files
`/assets/css/style.css` - Contains the Styling for Website
`/assets/js/main.js` - Contains the Scripts for Website
`/index.html` - Contains HTML code for the Website

#### To Reproduce
- just visit [https://gdscrgpv.github.io/gdscrgpv/](https://gdscrgpv.github.io/gdscrgpv/)
- Go to Top of the website (by default you will be already there)
- Scroll slowly and notice changes in the Header

#### Tasks
- [ ] Write the Styling in `/assets/css/style.css`
- [ ] Manipulate Onscroll function in `/assets/js/main.js`
- [ ] Chage HTML code in `/index.html`

**Comment by 120EE0692** [comment]
I want to work on this
